nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api/v1(?!/doc$)
    documentation:
        security:
            - Bearer: [ ]
        info:
            title: Pets Api
            description: Awesome app for control your pets
            version: 1.0.0
        # components:
        #     securitySchemes:
        #         Bearer:
        #         type: http
        #         scheme: bearer
        #         bearerFormat: JWT
        # paths:
        #     /api/v1/auth/login:
        #         post:
        #             summary: Login user
        #             tags:
        #                 - Auth
        #             requestBody:
        #                 description: Auth user
        #                 required: true
        #                 content:
        #                     application/json:
        #                         schema:
        #                         type: object
        #                         properties:
        #                             email:
        #                                 type: string
        #                             password:
        #                                 type: string
        #                         required:
        #                             - email
        #                             - password
        #             responses:
        #                 '200':
        #             description: Created
