nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Cache-Control', 'Content-Disposition', 'X-Suggested-Filename']
        expose_headers: ['Link', 'Content-Disposition', 'X-Suggested-Filename']
        max_age: 3600
    paths:
        '^/': null
