security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: argon2i

    providers:
        app_user_provider:
            id: App\User\Infrastructure\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/auth/login
            stateless: true
            json_login:
                check_path: /api/v1/auth/login
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/v1/auth/token-refresh

    access_control:
        - { path: ^/api,                          roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/login$,           roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/token-refresh,    roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/register/user,         roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/doc,                   roles: PUBLIC_ACCESS }
        - { path: ^/api/,                         roles: IS_AUTHENTICATED_FULLY }
